# Generated by Django 3.2.5 on 2021-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=60)),
                ('CourseNumber', models.IntegerField(default='', max_length=10)),
                ('InstructorName', models.CharField(default='', max_length=60)),
                ('Duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
    ]
