# Generated by Django 3.2.5 on 2021-07-17 18:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
    ]
